-- Devices, installs and ratings: the three things the dashboard needs and
-- nobody was recording.
--
-- These tables exist NOW, empty, and get seeded with demo rows so the console
-- has something to draw. That ordering is deliberate and is the whole point:
-- the dashboard queries these tables for real, so when actual devices start
-- reporting, the same queries return actual numbers and no code changes. The
-- fake part is the rows, not the reporting path — which is the opposite of
-- hardcoding numbers into a component and having to unpick them later.
--
-- WHY THE AUDIT LOG COULD NOT ANSWER THIS. `audit_events` records that a
-- download ticket was ISSUED. It cannot record whether the install succeeded,
-- because that happens on the device after the bytes have left — and the gap
-- between the two is exactly the number anybody actually wants.
--
-- As with 0002-0013, the statement-breakpoint marker is deliberately never
-- spelled out in this file.
CREATE TYPE "install_outcome" AS ENUM ('installed', 'updated', 'failed', 'removed');

CREATE TABLE "devices" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "org_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  -- Generated by the app on first run and kept in its own storage. NOT an
  -- advertising id or a hardware serial: those are either restricted, or
  -- personal data we would then have to justify holding.
  "device_key" text NOT NULL,
  "platform" "app_platform" NOT NULL,
  "model" text DEFAULT '' NOT NULL,
  "os_version" text DEFAULT '' NOT NULL,
  -- Which MAYA build is reporting, so "how many are on the old client" is
  -- answerable without asking anybody.
  "client_version" text DEFAULT '' NOT NULL,
  "first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
  "last_seen_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "devices" ADD CONSTRAINT "devices_org_id_fk"
  FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "devices" ADD CONSTRAINT "devices_user_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;

-- One row per physical install. Re-registering the same key updates the row
-- rather than growing a second one, or "how many devices" counts app restarts.
CREATE UNIQUE INDEX "devices_org_key" ON "devices" ("org_id","device_key");
CREATE INDEX "devices_user_idx" ON "devices" ("org_id","user_id");

CREATE TABLE "install_events" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "org_id" uuid NOT NULL,
  "device_id" uuid NOT NULL,
  "app_id" uuid NOT NULL,
  -- Null survives deleting a release: the fact that somebody installed
  -- something outlives the row describing what they installed.
  "release_id" uuid,
  "version" text NOT NULL,
  "outcome" "install_outcome" NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "install_events" ADD CONSTRAINT "install_events_org_id_fk"
  FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "install_events" ADD CONSTRAINT "install_events_device_id_fk"
  FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "install_events" ADD CONSTRAINT "install_events_app_id_fk"
  FOREIGN KEY ("app_id") REFERENCES "public"."apps"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "install_events" ADD CONSTRAINT "install_events_release_id_fk"
  FOREIGN KEY ("release_id") REFERENCES "public"."releases"("id") ON DELETE set null ON UPDATE no action;

CREATE INDEX "install_events_app_idx" ON "install_events" ("org_id","app_id","created_at");
CREATE INDEX "install_events_device_idx" ON "install_events" ("device_id","created_at");

-- Ratings. Parked as a FEATURE — nothing writes these yet — but the table
-- exists now so the dashboard reads a real column, and so the shape is decided
-- while it is cheap rather than under pressure later.
CREATE TABLE "app_ratings" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "org_id" uuid NOT NULL,
  "app_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "score" smallint NOT NULL,
  -- Tied to the version rated, so a fixed bug does not carry its old score
  -- around forever.
  "version" text DEFAULT '' NOT NULL,
  "comment" text DEFAULT '' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "app_ratings" ADD CONSTRAINT "app_ratings_org_id_fk"
  FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "app_ratings" ADD CONSTRAINT "app_ratings_app_id_fk"
  FOREIGN KEY ("app_id") REFERENCES "public"."apps"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "app_ratings" ADD CONSTRAINT "app_ratings_user_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "app_ratings" ADD CONSTRAINT "app_ratings_score_range"
  CHECK ("score" BETWEEN 1 AND 5);

-- One rating per person per app, editable. Without this a single frustrated
-- afternoon can move an app's average on its own.
CREATE UNIQUE INDEX "app_ratings_app_user_key" ON "app_ratings" ("app_id","user_id");
CREATE INDEX "app_ratings_app_idx" ON "app_ratings" ("org_id","app_id");

-- All three carry org_id, so rls-invariants.spec.ts requires row security
-- ENABLEd, FORCEd and policed. NULLIF for the same reason as 0002.
ALTER TABLE devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE devices FORCE ROW LEVEL SECURITY;
CREATE POLICY devices_tenant_isolation ON devices
  USING      (org_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK (org_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE install_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE install_events FORCE ROW LEVEL SECURITY;
CREATE POLICY install_events_tenant_isolation ON install_events
  USING      (org_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK (org_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

ALTER TABLE app_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_ratings FORCE ROW LEVEL SECURITY;
CREATE POLICY app_ratings_tenant_isolation ON app_ratings
  USING      (org_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
  WITH CHECK (org_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
