import { Body, Controller, HttpCode, Post, Req } from '@nestjs/common'
import { ZodValidationPipe } from 'nestjs-zod'
import { z } from 'zod'

import { DevicesService, type DeviceInput, type InstallReport } from './devices.service'

interface AuthedRequest {
  auth?: { sub: string; orgId: string }
}

const deviceSchema = z.object({
  // Generated by the app, so bounded rather than trusted for shape.
  deviceKey: z.string().min(8).max(128),
  platform: z.enum(['android', 'ios']),
  model: z.string().max(120).default(''),
  osVersion: z.string().max(60).default(''),
  clientVersion: z.string().max(60).default(''),
})

const installSchema = z.object({
  deviceKey: z.string().min(8).max(128),
  appSlug: z.string().min(1).max(120),
  version: z.string().min(1).max(120),
  outcome: z.enum(['installed', 'updated', 'failed', 'removed']),
})

/**
 * Where a device reports on itself.
 *
 * No @Roles: every signed-in member reaches this, because every one of them
 * has a phone and the whole point is that ordinary use produces the numbers.
 * Restricting it to staff would leave the dashboard measuring the four people
 * who administer the store rather than the company that uses it.
 */
@Controller('devices')
export class DevicesController {
  constructor(private readonly devices: DevicesService) {}

  private identity(req: AuthedRequest): { orgId: string; userId: string } {
    const auth = req.auth
    if (!auth) throw new Error('DevicesController reached without authentication')
    return { orgId: auth.orgId, userId: auth.sub }
  }

  @Post()
  @HttpCode(200)
  register(
    @Req() req: AuthedRequest,
    @Body(new ZodValidationPipe(deviceSchema)) body: DeviceInput,
  ): Promise<{ id: string }> {
    const { orgId, userId } = this.identity(req)
    return this.devices.register(orgId, userId, body)
  }

  @Post('install-events')
  @HttpCode(204)
  async recordInstall(
    @Req() req: AuthedRequest,
    @Body(new ZodValidationPipe(installSchema)) body: InstallReport,
  ): Promise<void> {
    const { orgId, userId } = this.identity(req)
    await this.devices.recordInstall(orgId, userId, body)
  }
}
