import AsyncStorage from '@react-native-async-storage/async-storage';

const KEY = 'maya.device.key.v1';

let cached: string | null = null;

/**
 * A stable identifier for this installation of MAYA.
 *
 * Generated by the app and stored in its own sandbox. Deliberately NOT a
 * hardware identifier: Android's are restricted and iOS's are deliberately
 * unstable, and both are personal data this product has no reason to hold. All
 * the server needs is something that stays the same across launches, so
 * "devices" does not become a count of app starts.
 *
 * Built from Math.random rather than a crypto library, and that is a real
 * decision rather than laziness: this is a NAME, not a secret. Nothing is
 * authorised by holding it — the bearer token does that — so the only property
 * that matters is not colliding, and 128 bits of it will not. Pulling in
 * expo-crypto for one identifier would be a dependency on the critical path of
 * a cold start, on the low-end hardware this app has to stay quick on.
 *
 * It dies with the app: uninstalling and reinstalling produces a new key, and
 * therefore a new device row. That is the honest answer — a fresh install IS a
 * fresh install, and pretending otherwise would need exactly the durable
 * hardware id being avoided here.
 */
const generate = (): string => {
  const chunk = (): string => Math.random().toString(36).slice(2, 12);
  return `${Date.now().toString(36)}-${chunk()}-${chunk()}-${chunk()}`;
};

export const deviceKey = async (): Promise<string> => {
  if (cached) return cached;

  const existing = await AsyncStorage.getItem(KEY);
  if (existing) {
    cached = existing;
    return existing;
  }

  const created = generate();
  await AsyncStorage.setItem(KEY, created);
  cached = created;
  return created;
};
