/**
 * Turns an unDraw illustration into a themed react-native-svg component.
 *
 *     node scripts/undraw.mjs apps_0l3h Catalog
 *
 * unDraw art is drawn for a white page: mid-greys for surfaces, near-black for
 * figures, and one accent (#6c63ff) meant to be swapped for a brand colour.
 * Dropped unmodified into this app it would fail twice — the purple fights the
 * coral, and on the near-black dark theme the near-black figures disappear.
 *
 * So nothing here keeps a literal colour. Every fill is rewritten to a slot on
 * the illustration palette, and the palette resolves per theme (see
 * illustrations/palette.ts). That is what makes one illustration legible on
 * both grounds instead of one.
 *
 * Checked in rather than run once and forgotten: adding a fourth slide should
 * be a command, not an afternoon of hand-editing path elements.
 */
import { writeFileSync } from 'node:fs'

/**
 * unDraw's fixed palette, mapped onto slots this app can theme.
 *
 * Skin tones are deliberately NOT themed. They are the one part of the drawing
 * that depicts something real, and lightening them for the dark theme would
 * change who is pictured rather than how the picture is lit.
 */
const COLOR_SLOTS = {
  '#6c63ff': 'accent',
  '#575a89': 'accentDeep',
  '#3f3d56': 'inkSoft',
  '#2f2e41': 'ink',
  '#e6e6e6': 'paper',
  '#f2f2f2': 'paper',
  '#f1f1f1': 'paper',
  '#f0f0f0': 'paper',
  '#f9f9f9': 'paper',
  '#e4e4e4': 'paper',
  '#ffffff': 'paper',
  '#fff': 'paper',
  '#cacaca': 'line',
  '#cbcbcb': 'line',
  '#ccc': 'line',
  '#ddd': 'line',
  '#d1d1d1': 'line',
  '#a0616a': 'skinShade',
  '#9f616a': 'skinShade',
  '#ffb8b8': 'skin',
  '#ffb6b6': 'skin',
}

const TAGS = {
  path: 'Path',
  rect: 'Rect',
  circle: 'Circle',
  ellipse: 'Ellipse',
  polygon: 'Polygon',
  g: 'G',
}

// Carried through as-is. Everything else — id, data-name, xmlns, style — is
// authoring metadata that react-native-svg has no use for.
const KEEP = new Set([
  'd', 'points', 'cx', 'cy', 'r', 'rx', 'ry',
  'x', 'y', 'width', 'height', 'opacity', 'transform',
])

const [slug, name] = process.argv.slice(2)
if (!slug || !name) {
  console.error('usage: node scripts/undraw.mjs <undraw-slug> <ComponentName>')
  process.exit(1)
}

const url = `https://cdn.undraw.co/illustrations/${slug}.svg`
const svg = await fetch(url).then((r) => {
  if (!r.ok) throw new Error(`${url} -> ${r.status}`)
  return r.text()
})

const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]
if (!viewBox) throw new Error('no viewBox')

const unknown = new Set()

const attrs = (raw) => {
  const out = []
  for (const [, key, value] of raw.matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) {
    if (key === 'fill') {
      const slot = COLOR_SLOTS[value.toLowerCase()]
      if (!slot) unknown.add(value)
      out.push(`fill={c.${slot ?? 'ink'}}`)
    } else if (KEEP.has(key)) {
      out.push(`${key}="${value}"`)
    }
  }
  return out.join(' ')
}

const body = []
for (const [, close, tag, raw] of svg.matchAll(/<(\/?)([a-zA-Z]+)([^>]*?)\/?>/g)) {
  const mapped = TAGS[tag]
  if (!mapped) continue
  if (close) {
    body.push(`</${mapped}>`)
  } else {
    const a = attrs(raw)
    // Only <g> ever wraps children here; every shape element self-closes.
    body.push(tag === 'g' ? `<${mapped}>` : `<${mapped} ${a} />`)
  }
}

if (unknown.size) {
  console.warn(`  ! unmapped fills, defaulted to ink: ${[...unknown].join(', ')}`)
}

const file = `/**
 * unDraw "${slug}", themed. Generated by scripts/undraw.mjs — do not hand-edit;
 * re-run the script instead.
 *
 * Source: ${url}
 * unDraw is free for any use, with no attribution required.
 */

import Svg, { ${[...new Set(body.map((b) => b.match(/<\/?([A-Z][a-zA-Z]*)/)?.[1]).filter(Boolean))].sort().join(', ')} } from 'react-native-svg';

import { useIllustrationPalette, type IllustrationProps } from './palette';

export const ${name} = ({ width, height }: IllustrationProps) => {
  const c = useIllustrationPalette();

  return (
    <Svg width={width} height={height} viewBox="${viewBox}" fill="none">
      ${body.join('\n      ')}
    </Svg>
  );
};
`

const out = `src/components/illustrations/${name}.tsx`
writeFileSync(out, file)
console.log(`  ${slug} -> ${out} (${body.length} elements, ${(file.length / 1024).toFixed(1)} kB)`)
